export const GET_PRODUCT = 'GETPRODUCT'
export const GET_USERS = 'GETUSERS'
export const ADD_CART = 'ADDCART'

// export const DECREMENT_COUNT_PAY = 'DECREMENTCOUNTPAY'
// export const DECREMENT_COUNT_PAY_PROFILE = 'DECREMENTCOUNTPAYPROFILE'
// export const DECREMENT_COUNT_PAY_BY_CART = 'DECREMENTCOUNTPAYBYCART'
// export const INCREMENT_COUNT_PAY_BY_CART = 'INCREMENTCOUNTPAYBYCART'
//export const ONCHANGE_NUMBER_INPUT_BY_CART = 'ONCHANGENUMBERINPUTBYCART'

// ------- cart
export const INCREMENT_PROJECT = 'INCREMENTPROJECT'
export const DECREMENT_PROJECT = 'DECREMENTPROJECT'
export const DELETE_ITEM_CART = 'DELETEITEMCART'
export const DELETE_LIST_ITEM_CART = 'DELETELISTITEMCART'
export const NUMBER_INPUT = 'NUMBERINPUT'
export const PAY_CART = 'PAYCART'
export const KEYWORD_SEARCH = 'KEYWORDSORT'
export const ADD_CART_BY_PROFILE = 'ADDCARTBYPROFILE'


export const SET_EVALUATE = 'SETEVALUATE'

export const DELETE_ITEM_BY_PAY_CART = 'DELETEITEMBYPAYCART'

// cart no user
export const PAY_CART_NO_USER = 'PAYCARTNOUSER'
export const ADD_CART_NO_USER = 'ADDCARTNOUSER'
export const ADD_CART_BY_PROFILE_NO_USER = 'ADDCARTBYPROFILENOUSER'

export const INCREMENT_PROJECT_NO_USER = 'INCREMENTPROJECTNOUSER'
export const DECREMENT_PROJECT_NO_USER = 'DECREMENTPROJECTNOUSER'
export const DELETE_ITEM_CART_NO_USER = 'DELETEITEMCARTNOUSER'
export const DELETE_LIST_ITEM_CART_NO_USER = 'DELETELISTITEMCARTNOUSER'
export const NUMBER_INPUT_NO_USER = 'NUMBERINPUTNOUSER'

export const PUSH_CART_LOCAL_IN_CART_USER = 'PUSHCARTLOCALINCARTUSER'

// add order

export const ADD_ORDER = 'ADDORDER'
export const ADD_ORDER_NO_USER = 'ADDORDERNOUSER'
